sudo: required
dist: trusty
git:
        submodules: false
language: c
compiler: gcc
before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y qemu-system-x86 nasm texinfo libmpfr-dev libmpc-dev libgmp-dev libisl-dev flex bison
        - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
        - git submodule update --init hermit/lwip hermit/usr/gcc hermit/usr/pte hermit/usr/libomp
script:
        - ./configure
        - wget https://www.lankes.org/deploy/newlib.tar.gz
        - tar xzf newlib.tar.gz
        - mv tmp hermit/usr/
        - mv x86 hermit/usr/
        - make T=1 travis
        - sudo echo $PROXY_STR > /proc/sys/fs/binfmt_misc/register
env:
        global:
                - TOPDIR=`pwd`/../..
                - PROXY_STR=":hermit:M:7:\\x42::`pwd`/RWTH-OS/HermitCore/hermit/tools/proxy"
                - HERMIT_ISLE=qemu
                - HERMIT_CPUS=2
                - HERMIT_MEM="128M"
