sudo: required
dist: trusty
git:
        submodules: false
language: c
compiler: gcc
before_install:
        - sudo apt-get update
        - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
        - git submodule update --init --recursive
install:
        - sudo apt-get install nasm texinfo libmpfr-dev libmpc-dev libgmp-dev libisl-dev
before_script:
        - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
        - export PATH=$PATH:/usr/local/bin
