sudo: required
dist: trusty
git:
        submodules: false
language: c
compiler: gcc
before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y curl qemu-system-x86 nasm texinfo libmpfr-dev libmpc-dev libgmp-dev libisl-dev flex bison
        - git submodule update --init hermit/lwip hermit/usr/gcc hermit/usr/pte hermit/usr/libomp
script:
        - ./configure
        - wget https://www.lankes.org/deploy/newlib.tar.gz
        - tar xzf newlib.tar.gz
        - mv tmp hermit/usr/
        - mv x86 hermit/usr/
        - make T=1 travis
        - make test
env:
        global:
                - TOPDIR=`pwd`/../..
                - PROXY_STR=":hermit:M:7:\\x42::`pwd`/RWTH-OS/HermitCore/hermit/tools/proxy"
                - HERMIT_ISLE=qemu
                - HERMIT_CPUS=1
                - HERMIT_MEM="512M"
                - HERMIT_KVM="0"
                - HERMIT_VERBOSE="1"
                - HERMIT_APP_PORT=8000
