sudo: required
dist: trusty
git:
        submodules: false
language: c
compiler: gcc
before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y nasm texinfo libmpfr-dev libmpc-dev libgmp-dev libisl-dev
        - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
        - git submodule update --init hermit/lwip hermit/usr/gcc hermit/usr/pte hermit/usr/newlib hermit/usr/libomp
script:
        - ./configure
        - wget https://www.lankes.org/deploy/bzImage
        - mkdir -p linux/arch/x86/boot/
        - mv bzImage linux/arch/x86/boot/
        - wget https://www.lankes.org/deploy/bootstrap.tar.gz
        - tar xzf bootstrap.tar.gz
        - mv tmp hermit/usr/
        - mv x86 hermit/usr/
        - make
env:
        global:
                - TOPDIR=`pwd`/../..
